In [1]:
import numpy as np
import pandas as pd

In [2]:
nums = [3, 5, 7, 8, 12]
cubes = []

# Appending the cubes of elements in nums to the cubes list
for num in nums:
    cubes.append(num ** 3)

# Print the cubes list
print(cubes)


[27, 125, 343, 512, 1728]


In [3]:
# Creating an empty dictionary
dict = {}

# Adding the key-value pairs
dict['parrot'] = 2
dict['goat'] = 4
dict['spider'] = 8
dict['crab'] = 10

# Print the dictionary
print(dict)


{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [4]:
# Initialize a variable for the total number of legs
total_legs = 0

# Looping through the dictionary items
for animal, legs in dict.items():
    print(f"{animal}: {legs} legs")
    total_legs += legs

# Print the total number of legs
print(f"Total legs: {total_legs}")


parrot: 2 legs
goat: 4 legs
spider: 8 legs
crab: 10 legs
Total legs: 24


In [5]:
# Creating a tuple with a list inside
A = (3, 9, 4, [5, 6])

# Changing the value 5 to 8 in the list inside the tuple
A[3][0] = 8

# Print the modified tuple
print(A)


(3, 9, 4, [8, 6])


In [6]:
# Deleting the tuple A
del A


In [7]:
# Creating the tuple
B = ('a', 'p', 'p', 'l', 'e')

# Counting the number of occurrences of 'p'
count_p = B.count('p')

# Print the count of 'p'
print(f"Occurrences of 'p': {count_p}")


Occurrences of 'p': 2


In [8]:
# Finding the index of 'l' in tuple B
index_l = B.index('l')

# Print the index of 'l'
print(f"Index of 'l': {index_l}")


Index of 'l': 3


In [9]:
# Define matrix A
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Define vector z
z = np.array([1, 0, 1])
# 2.1 Convert matrix A into numpy array (already defined as a numpy array)
print("Matrix A as a NumPy array:\n", A)


Matrix A as a NumPy array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
# 2.2 Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2.
b = A[:2, :2]
print("Subarray b (first 2 rows and columns 1 and 2):\n", b)


Subarray b (first 2 rows and columns 1 and 2):
 [[1 2]
 [5 6]]


In [11]:
# 2.3 Create an empty matrix 'C' with the same shape as 'A'
C = np.empty_like(A)
print("Empty matrix C with the same shape as A:\n", C)


Empty matrix C with the same shape as A:
 [[1936286034 1918967909 1701672295  544437358]
 [1881173876 1919252335 1701602592 1953391981]
 [1936291629        101          0          0]]


In [12]:
# 2.4 Add the vector z to each column of the matrix 'A' with an explicit loop and store it in 'C'
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
for i in range(A.shape[1]):
    C[:, i] = A[:, i] + z
print("Matrix C after adding vector z to each column of A:\n", C)

# Define X, Y, and v
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])

Matrix C after adding vector z to each column of A:
 [[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


In [13]:
# 2.5 Add and print the matrices X and Y
sum_XY = np.add(X, Y)  # Or X + Y
print("Sum of matrices X and Y:\n", sum_XY)


Sum of matrices X and Y:
 [[ 6  8]
 [10 12]]


In [14]:
# 2.6 Multiply and print the matrices X and Y (element-wise multiplication)
product_XY = np.multiply(X, Y)  # Or X * Y
print("Element-wise multiplication of X and Y:\n", product_XY)


Element-wise multiplication of X and Y:
 [[ 5 12]
 [21 32]]


In [15]:
# 2.7 Compute and print the element-wise square root of matrix Y
sqrt_Y = np.sqrt(Y)
print("Element-wise square root of matrix Y:\n", sqrt_Y)


Element-wise square root of matrix Y:
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [16]:
# 2.8 Compute and print the dot product of the matrix X and vector v
dot_product = np.dot(X, v)
print("Dot product of matrix X and vector v:\n", dot_product)


Dot product of matrix X and vector v:
 [29 67]


In [17]:
# 2.9 Compute and print the sum of each column of X
column_sum = np.sum(X, axis=0)
print("Sum of each column of matrix X:\n", column_sum)


Sum of each column of matrix X:
 [4 6]


In [18]:
# 3.1 Define the function Compute
def Compute(distance, time):
    if time == 0:
        return "Time cannot be zero!"
    else:
        velocity = distance / time
        return velocity

# Example usage
distance = 100  # meters
time = 10  # seconds
velocity = Compute(distance, time)
print(f"Velocity = {velocity} m/s")


Velocity = 10.0 m/s


In [19]:
# 3.2 Create the list of even numbers up to 12
even_num = [2, 4, 6, 8, 10, 12]

# Define the function mult
def mult(even_num):
    product = 1  # Start with 1 as the identity element for multiplication
    for num in even_num:
        product *= num
    return product

# Example usage
result = mult(even_num)
print(f"The product of all even numbers is: {result}")


The product of all even numbers is: 46080


In [20]:
# 4. Create the DataFrame 'pd'
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

# Create DataFrame
df = pd.DataFrame(data)
print("DataFrame 'pd':\n", df)

# 4.1 Print only the first two rows of the dataframe
print("\n4.1 First two rows:\n", df.head(2))

DataFrame 'pd':
    C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8

4.1 First two rows:
    C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [21]:
# 4.2 Print the second column
print("\n4.2 Second column:\n", df['C2'])


4.2 Second column:
 0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [22]:
# 4.3 Change the name of the third column from ‘C3’ to ‘B3’
df.rename(columns={'C3': 'B3'}, inplace=True)
print("\n4.3 DataFrame after renaming column 'C3' to 'B3':\n", df)


4.3 DataFrame after renaming column 'C3' to 'B3':
    C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [23]:
# 4.4 Add a new column to the dataframe and name it ‘Sum’
df['Sum'] = 0
print("\n4.4 DataFrame after adding column 'Sum':\n", df)


4.4 DataFrame after adding column 'Sum':
    C1  C2  B3  C4  Sum
0   1   6   7   7    0
1   2   7   9   5    0
2   3   5   8   2    0
3   5   4   6   8    0
4   5   8   5   8    0


In [24]:
# 4.5 Sum the entries of each row and add the result in the column ‘Sum’
df['Sum'] = df.sum(axis=1)
print("\n4.5 DataFrame after summing rows and adding to 'Sum':\n", df)


4.5 DataFrame after summing rows and adding to 'Sum':
    C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [25]:
# 4.6 Read CSV file 'hello_sample.csv' into a Pandas dataframe
# Assuming 'hello_sample.csv' is located in the same directory or provided path
# For example purposes, I'll simulate this part:
df_csv = pd.read_csv('datasets/hello_sample.csv')
# For now, skipping this due to the lack of actual file in the current environment

In [26]:
# 4.7 Print complete dataframe (assuming the csv is loaded)
print("\n4.7 Complete DataFrame:\n", df_csv)


4.7 Complete DataFrame:
     Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [27]:
# 4.8 Print only the bottom 2 records of the dataframe
print("\n4.8 Bottom 2 records:\n", df_csv.tail(2))


4.8 Bottom 2 records:
    Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [28]:
# 4.9 Print information about the dataframe
print("\n4.9 Information about the DataFrame:\n")
df_csv.info()


4.9 Information about the DataFrame:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes


In [29]:
# 4.10 Print shape (rows x columns) of the dataframe
print("\n4.10 Shape of the DataFrame:\n", df_csv.shape)


4.10 Shape of the DataFrame:
 (23, 4)


In [30]:
# 4.11 Sort the data of the dataframe using column ‘Weight’
# Assuming 'Weight' column exists in the CSV file
df_sorted = df_csv.sort_values(by='Weight')
print("\n4.11 DataFrame sorted by 'Weight':\n", df_sorted)


4.11 DataFrame sorted by 'Weight':
     Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [31]:
# 4.12 Use isnull() and dropna() methods and see if they produce changes
# Checking for missing values
print("\n4.12 Checking for missing values (isnull):\n", df_csv.isnull())


4.12 Checking for missing values (isnull):
     Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False


In [32]:
# Dropping rows with missing values (if any)
df_dropped_na = df_csv.dropna()
print("\n4.12 DataFrame after using dropna:\n", df_dropped_na)


4.12 DataFrame after using dropna:
     Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66
